parent = "alpine-root"

recipes = [
    "core/rpi-alpine-setup",
    # Install Rugix Ctrl into the image.
    "core/rugix-ctrl",
    "core/ssh",
]

[parameters."core/ssh"]
root_authorized_keys = """
<INSERT YOUR PUBLIC SSH KEY HERE>
"""
