[repositories]
rugpi-extra = { git = "https://github.com/silitics/rugpi-extra.git", branch = "v0.6" }

[images.generic-amd64]
layer = "generic-amd64"
architecture = "amd64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.generic-amd64-vm]
layer = "generic-amd64"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"

[images.generic-arm64]
layer = "generic-arm64"
architecture = "arm64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.generic-arm64-vm]
layer = "generic-arm64"
architecture = "arm64"
target = "generic-grub-efi"
size = "16G"
