[package]
name = "rugpi-common"
description = "Common utilities for Rugpi Ctrl and Rugpi Bakery."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
crc32fast = "1.3.2"
indoc = "2.0.3"
serde.workspace = true
thiserror = "1.0.50"
xscript.workspace = true

[dev-dependencies]
clap.workspace = true
