[package]
name = "rugpi-common"
description = "Common utilities for Rugpi Ctrl and Rugpi Bakery."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
indoc = "2.0.3"
xscript.workspace = true
