[package]
name = "rugpi-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
camino = "1.1.6"
indoc = "2.0.3"
xscript = "0.1.2"
