[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.package]
authors = ["Silitics GmbH <info@silitics.com>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/silitics/rugpi/"
homepage = "https://oss.silitics.com/rugpi/"

[workspace.dependencies]
anyhow = "1.0.71"
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
nix = { version = "0.28", features = ["ioctl", "fs", "mount", "process"] }
xscript = "0.3.0"
