[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.package]
authors = ["Silitics GmbH <info@silitics.com>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/silitics/rugpi/"
homepage = "https://oss.silitics.com/rugpi/"

[workspace.dependencies]
bytes = "1.7.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
nix = { version = "0.29", features = ["ioctl", "fs", "mount", "process"] }
xscript = "0.3.0"
tracing = "0.1"
rugpi-common = { path = "crates/rugpi-common" }
reportify = { path = "crates/reportify" }

[workspace.lints.clippy]
needless_borrows_for_generic_args = "allow"
new_without_default = "allow"