[bundle]
name = "rugix_bakery"
version = "1"
description = "Sidex schema for Rugix Bakery."
authors = ["Silitics GmbH <info@silitics.com>"]

[backend.json-schema]

[backend.rust]
derive = ["Clone", "Debug"]
plugins = ["builder", "serde"]

[backend.rust.plugin.serde]
sidex_serde_path = "::sidex_serde"
