# We use Alpine Linux 3.20 as a basis.
parent = "core/alpine-3-20"

recipes = [
    # Setup Alpine for booting via Grub.
    "core/alpine-grub-setup",
    # Persist `/root`.
    "core/persist-root-home",
    # Install a static website.
    "hello-world",
]
