[bundle]
name = "rugix_ctrl"
version = "1"
description = "Sidex schema for Rugix Ctrl."
authors = ["Silitics GmbH <info@silitics.com>"]

[backend.json-schema]

[backend.rust]
derive = ["Clone", "Debug"]
plugins = ["builder", "serde"]

[backend.rust.plugin.serde]
sidex_serde_path = "::sidex_serde"

[backend.rust.types.table]
"::core::builtins::Map" = "indexmap::IndexMap"