[repositories]
rugix-extra = { git = "https://github.com/silitics/rugix-extra.git" }

[systems.customized-arm64]
layer = "yocto-customized"
architecture = "arm64"
target = "generic-grub-efi"

[systems.customized-amd64]
layer = "yocto-customized"
architecture = "amd64"
target = "generic-grub-efi"
