[repositories]
rugpi-extra = { git = "https://github.com/silitics/rugpi-extra.git" }

[images.customized-arm64]
layer = "yocto-customized"
architecture = "arm64"
target = "generic-grub-efi"

[images.customized-arm64-vm]
layer = "yocto-customized"
architecture = "arm64"
target = "generic-grub-efi"
size = "16G"

[images.customized-amd64]
layer = "yocto-customized"
architecture = "amd64"
target = "generic-grub-efi"

[images.customized-amd64-vm]
layer = "yocto-customized"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"