[repositories]
rugpi-extra = { git = "https://github.com/silitics/rugpi-extra.git", branch = "v0.6" }

[images.customized-amd64]
layer = "customized"
architecture = "amd64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.customized-amd64-vm]
layer = "customized"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"

[images.customized-arm64]
layer = "customized"
architecture = "arm64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.customized-arm64-vm]
layer = "customized"
architecture = "arm64"
target = "generic-grub-efi"
size = "16G"
