[package]
name = "rugix-blocking"
edition = "2021"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio.workspace = true

[lints]
workspace = true
