name: Check and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-and-lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Clippy
        run: cargo clippy --all-targets --all-features

      - name: Format
        run: cargo +nightly fmt --check
