name: Check and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-and-lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v2

      - name: Install Nightly Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Clippy
        run: cargo +nightly clippy --all-targets --all-features
      
      - name: Test
        run: cargo +nightly test --all-features

      - name: Format
        run: cargo +nightly fmt --check
